### ISSUE TITLE
move to koajs organization

### ISSUE THREAD

**Issue by jonathanong** [gyson/koa-convert#2]
i've invited you to be part of the @koajs/koa-v2 team in @koajs. i'd like you to transfer your repo over. i'm not sure how transferring works when you're not an owner of the organization, though. let me know if you run into any issues.

**Comment by gyson** [comment]
I agree that koajs org is a better place to host this repository.

Do I need to add more collaborator on npm registry?

**Comment by jonathanong** [comment]
Sure. I think it's only necessary when you no longer have time to maintain this yoursef

**Comment by gyson** [comment]
Should we rename it as `koajs/convert`?

If yes, can you rename it? I have no permission to do rename.

**Comment by jonathanong** [comment]
Done :)
