### ISSUE TITLE
Passing arguments v1.x into middleware?

### ISSUE THREAD

**Issue by ifiokjr** [gyson/koa-convert#3]
Currently I can't figure out an elegant way for passing arguments into v1.x middleware. 

Is this something that could be useful to anyone?

I'm using the koa-ratelimiter library which currently doesn't have v2.x support. However I'd like to also pass in arguments. 

The old version looked like [this](https://github.com/koajs/api-boilerplate/blob/master/index.js#L53)

``` javascript
app.use(ratelimit({
  max: opts.ratelimit,
  duration: opts.duration,
  db: redis.createClient()
}));
```

What I'd like to do is pass in the options as a second parameter to `convert`.

``` javascript
app.use(convert(ratelimit, {
  max: opts.ratelimit,
  duration: opts.duration,
  db: redis.createClient()
}));
```

**Comment by ifiokjr** [comment]
Okay, what I've ended up going with is the following. 

``` javascript
...
const ratelimit = require('koa-ratelimit');

const _ratelimit = ratelimit.bind(undefined, {
  max: opts.ratelimit,
  duration: opts.duration,
  db: redis.createClient()
});
_ratelimit._name = ratelimit._name || ratelimit.name;
app.use(convert(_ratelimit));

```

It hasn't broken anything quite yet. But I'm not 100% how reliable a hack it is. 

Any suggestions?

**Comment by ifiokjr** [comment]
Oh.. Just realised my mistake. 

The example from the `README.md` was showing a direct generator middleware function. My code was failing for other reasons when using convert the way it was meant to be used. 

_**Closing this as a non-issue.**_ 😶

**Comment by gyson** [comment]
I think you should do this:

``` js
app.use(convert(ratelimit({
  max: opts.ratelimit,
  duration: opts.duration,
  db: redis.createClient()
})));
```

**Comment by ifiokjr** [comment]
Haha! Yep yep figured it out in the end.
