### ISSUE TITLE
throws error if `next` not defined

### ISSUE THREAD

**Issue by azhang** [gyson/koa-convert#5]
I'd like to be able to call converted middleware without a `next` param, similar to what happens in compose (https://github.com/koajs/compose/blob/master/index.js#L20). For example, using koa 2.x params middleware:

``` js
async function noop () {}
export async function organizationIdParam (id, ctx, next) {
  await convert(rbac.allow('read:organization', { organization: id }))(ctx, noop);
  ctx.organization = await Organization.findById(id);
  await next();
}
```

It would be nice to instead be able to call it like this:

``` js
export async function organizationIdParam (id, ctx, next) {
  await convert(rbac.allow('read:organization', { organization: id }))(ctx);
  ctx.organization = await Organization.findById(id);
  await next();
}
```

What do you think?

**Comment by gyson** [comment]
Thanks your suggestion but I think this (your example) is a bad use case of koa middleware.
1. It creates and converts koa middleware for every requests, which is unnecessary.
2. It's error-prone. There might be a bug in your example code. 

In `rbac.allow` at https://github.com/yanickrochon/koa-rbac/blob/master/rbac.js#L115, it restricts permission by `return` and not calling `yield next`. In your example, `next` is just `noop` and user without permission will continue go through downstream.

**Comment by azhang** [comment]
You are right - I forgot to update this snippet when I encountered that bug. Here is how i'm handling this now:

```
export async function organizationIdParam (id, ctx, next) {
  await convert(rbac.allow('read:organization', { organization: id }))(ctx, noop);
  if (ctx.status === 403) return;

  ctx.organization = await Organization.findById(id);
  await next();
}
```

**Comment by gyson** [comment]
I would not recommend you to create middleware dynamically like this. It seems that your use case (inject id dynamically) has beyond the scope of that middleware. (I am not familiar with that middleware and I might be wrong).

Also, `ctx.status === 403` is hacking. I would suggest you to do it in this way:

``` js
export function organizationIdParam (id, ctx, next) { // or `async function` if you want
  return convert.compose(
    rbac.allow('read:organization', { organization: id }),
    async function (ctx, next) {
      ctx.organization = await Organization.findById(id);
      await next();
    }
  )(ctx, next);
}
```

**Comment by azhang** [comment]
Great, that makes sense. Thank you!
